app = "m-bank-spring"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
JAVA_OPTS = "-Xmx512m -XX:MaxRAM=512m"
SPRING_PROFILES_ACTIVE = "flyio"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "5s"
interval = "15s"
method = "get"
path = "/ping"
port = 8080
timeout = "2s"
type = "http"

[[http_service.checks]]
grace_period = "5s"
interval = "15s"
method = "get"
path = "/"
port = 8080
timeout = "2s"
type = "http"

[deploy]
strategy = "rolling"